export const options = {
  // Configurations Category
  theme: {
    primaryColor: "#A020F0",
    secondaryColor: "#f44336",
    fontFamily:
      "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', " +
      "'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', " +
      "sans-serif",
    showHeader: true,
    showFooter: false,
    showInputRow: true,
    actionDisabledIcon:
      "https://gigsar.s3.ap-south-1.amazonaws.com/icons/action+disabled.png",
    embedded: false,
    desktopEnabled: true,
    mobileEnabled: true,
    flowStartTrigger: "ON_CHATBOT_INTERACT",
  },
  tooltip: {
    mode: "CLOSE",
    text: "Talk to me! 😊",
  },
  chatButton: {
    icon: "https://gigsar.s3.ap-south-1.amazonaws.com/icons/message.png",
  },
  header: {
    title: <h3>Gigsar Chatbot</h3>,
    showAvatar: true,
    avatar: "https://gigsar.s3.ap-south-1.amazonaws.com/icons/botAvatar.png",
    closeChatIcon:
      "https://gigsar.s3.ap-south-1.amazonaws.com/icons/closeChat.png",
  },
  notification: {
    disabled: false,
    defaultToggledOn: true,
    volume: 1,
    icon: "https://gigsar.s3.ap-south-1.amazonaws.com/icons/notificationIcon.png",
    sound:
      "https://gigsar.s3.ap-south-1.amazonaws.com/icons/notification-sound.mp3",
    showCount: true,
  },
  audio: {
    disabled: false,
    defaultToggledOn: true,
    tapToPlay: true,
    language: "en-IN",
    voiceNames: ["Google हिंदी"],
    rate: 1,
    volume: 1,
    icon: "https://gigsar.s3.ap-south-1.amazonaws.com/icons/audioIcon.png",
  },
  chatHistory: {
    disabled: false,
    maxEntries: 30,
    storageKey: "rcb-history",
    viewChatHistoryButtonText: "Load Chat History ⟳",
    chatHistoryLineBreakText: "----- Previous Chat History -----",
    autoLoad: true,
  },
  chatInput: {
    disabled: false,
    allowNewline: false,
    enabledPlaceholderText: "Type your message...",
    disabledPlaceholderText: "",
    showCharacterCount: false,
    characterLimit: -1,
    botDelay: 1000,
    sendButtonIcon:
      "https://gigsar.s3.ap-south-1.amazonaws.com/icons/sendIcon.png",
    blockSpam: true,
    sendOptionOutput: true,
    sendCheckboxOutput: true,
    sendAttachmentOutput: true,
  },
  chatWindow: {
    showScrollbar: false,
    autoJumpToBottom: false,
    showMessagePrompt: true,
    messagePromptText: "New Messages ↓",
    messagePromptOffset: 30,
  },
  sensitiveInput: {
    maskInTextArea: true,
    maskInUserBubble: true,
    asterisksCount: 10,
    hideInUserBubble: false,
  },
  userBubble: {
    animate: true,
    showAvatar: false,
    avatar: "https://gigsar.s3.ap-south-1.amazonaws.com/icons/userAvatar.png",
    simStream: true,
    streamSpeed: 30,
    dangerouslySetInnerHtml: false,
  },
  botBubble: {
    animate: true,
    showAvatar: false,
    avatar: "https://gigsar.s3.ap-south-1.amazonaws.com/icons/botAvatar.png",
    simStream: true,
    streamSpeed: 50,
    dangerouslySetInnerHtml: false,
  },
  emoji: {
    disabled: false,
    icon: "https://gigsar.s3.ap-south-1.amazonaws.com/icons/emojiIcon.png",
    list: [
      "😀",
      "😃",
      "😄",
      "😅",
      "😊",
      "😌",
      "😇",
      "🙃",
      "🤣",
      "😍",
      "🥰",
      "🥳",
      "🎉",
      "🎈",
      "🚀",
      "⭐️",
    ],
  },
  advance: {
    useCustomMessages: false,
    useCustomBotOptions: false,
    useCustomPaths: false,
  },

  // Styles Category
  tooltipStyle: {},
  chatButtonStyle: {},
  notificationBadgeStyle: {},
  chatWindowStyle: {},
  headerStyle: {},
  bodyStyle: {},
  chatInputContainerStyle: {},
  chatInputAreaStyle: {},
  chatInputAreaFocusedStyle: {},
  chatInputAreaDisabledStyle: {},
  userBubbleStyle: {},
  botBubbleStyle: {},
  botOptionStyle: {},
  botOptionHoveredStyle: {},
  botCheckboxRowStyle: {},
  botCheckboxNextStyle: {},
  botCheckMarkStyle: {},
  botCheckMarkSelectedStyle: {},
  sendButtonStyle: {},
  sendButtonHoveredStyle: {},
  characterLimitStyle: {},
  characterLimitReachedStyle: {},
  chatHistoryButtonStyle: {},
  chatHistoryButtonHoveredStyle: {},
  chatHistoryLineBreakStyle: {},
  chatMessagePromptStyle: {},
  chatMessagePromptHoveredStyle: {},
  footerStyle: {},
  loadingSpinnerStyle: {},
};
