const comedyGenresOptions = [
  "Aggressive humour",
  "Alternative comedy",
  "Anecdotal comedy",
  "Anti-humor",
  "Black comedy",
  "Blue comedy",
  "Character comedy",
  "Cringe comedy",
  "Deadpan comedy",
  "Double act",
  "Gallows humor",
  "Improvisational comedy",
  "Insult comedy",
  "Musical comedy",
  "Observational comedy",
  "Physical comedy",
  "Prop comedy",
  "Satirical comedy",
  "Surreal humour",
  "Topical comedy",
  "Word play",
  "Slapstick comedy",
  "Situational comedy",
  "Stand-up comedy",
  "Sketch comedy",
  "Parody",
  "Spoof",
  "Farce",
  "Mockumentary",
  "One-line joke",
  "Practical joke",
  "Prank",
  "Slapstick",
  "Screwball comedy",
  "Romantic comedy",
  "Sitcom",
];
